schema_version = "1.0.0"

id = "storyblender"
version = "1.0.0"
name = "StoryBlender"
tagline = "Automated 3D Storyboard Generation with AI3"
maintainer = "StoryBlender"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "4.5.5"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/aiofiles-24.1.0-py3-none-any.whl",
  "./wheels/aiofiles-25.1.0-py3-none-any.whl",
  "./wheels/aiohappyeyeballs-2.6.1-py3-none-any.whl",
  "./wheels/aiohttp-3.13.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/aiohttp-3.13.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/aiohttp-3.13.3-cp311-cp311-win_amd64.whl",
  "./wheels/aiosignal-1.4.0-py3-none-any.whl",
  "./wheels/annotated_doc-0.0.4-py3-none-any.whl",
  "./wheels/annotated_types-0.7.0-py3-none-any.whl",
  "./wheels/anthropic-0.86.0-py3-none-any.whl",
  "./wheels/any_llm_sdk-0.7.0-py3-none-any.whl",
  "./wheels/any_llm_sdk-1.13.0-py3-none-any.whl",
  "./wheels/anyio-4.13.0-py3-none-any.whl",
  "./wheels/asttokens-3.0.1-py3-none-any.whl",
  "./wheels/attrs-26.1.0-py3-none-any.whl",
  "./wheels/beautifulsoup4-4.14.3-py3-none-any.whl",
  "./wheels/brotli-1.2.0-cp311-cp311-macosx_10_9_universal2.whl",
  "./wheels/brotli-1.2.0-cp311-cp311-win_amd64.whl",
  "./wheels/bunnycdnpython-0.0.8-py3-none-any.whl",
  "./wheels/cachetools-7.0.5-py3-none-any.whl",
  "./wheels/certifi-2026.2.25-py3-none-any.whl",
  "./wheels/cffi-2.0.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/cffi-2.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/charset_normalizer-3.4.6-cp311-cp311-macosx_10_9_universal2.whl",
  "./wheels/charset_normalizer-3.4.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/charset_normalizer-3.4.6-cp311-cp311-win_amd64.whl",
  "./wheels/click-8.3.1-py3-none-any.whl",
  "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
  "./wheels/coloredlogs-15.0.1-py2.py3-none-any.whl",
  "./wheels/contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/contourpy-1.3.3-cp311-cp311-win_amd64.whl",
  "./wheels/cryptography-46.0.6-cp311-abi3-macosx_10_9_universal2.whl",
  "./wheels/cryptography-46.0.6-cp311-abi3-win_amd64.whl",
  "./wheels/cycler-0.12.1-py3-none-any.whl",
  "./wheels/cython-3.2.4-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/cython-3.2.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/cython-3.2.4-cp311-cp311-win_amd64.whl",
  "./wheels/dataclasses_json-0.6.7-py3-none-any.whl",
  "./wheels/decorator-5.2.1-py3-none-any.whl",
  "./wheels/deprecated-1.3.1-py2.py3-none-any.whl",
  "./wheels/distro-1.9.0-py3-none-any.whl",
  "./wheels/docstring_parser-0.17.0-py3-none-any.whl",
  "./wheels/exceptiongroup-1.3.1-py3-none-any.whl",
  "./wheels/executing-2.2.1-py2.py3-none-any.whl",
  "./wheels/fastapi-0.125.0-py3-none-any.whl",
  "./wheels/fastapi-0.135.2-py3-none-any.whl",
  "./wheels/fastembed-0.8.0-py3-none-any.whl",
  "./wheels/fastuuid-0.14.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/fastuuid-0.14.0-cp311-cp311-win_amd64.whl",
  "./wheels/ffmpy-1.0.0-py3-none-any.whl",
  "./wheels/filelock-3.25.2-py3-none-any.whl",
  "./wheels/flatbuffers-25.12.19-py2.py3-none-any.whl",
  "./wheels/fonttools-4.62.1-cp311-cp311-macosx_10_9_universal2.whl",
  "./wheels/fonttools-4.62.1-cp311-cp311-win_amd64.whl",
  "./wheels/fonttools-4.62.1-py3-none-any.whl",
  "./wheels/frozenlist-1.8.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/frozenlist-1.8.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl",
  "./wheels/frozenlist-1.8.0-cp311-cp311-win_amd64.whl",
  "./wheels/fsspec-2026.2.0-py3-none-any.whl",
  "./wheels/genai-1.0.3-py3-none-any.whl",
  "./wheels/genai-2.1.0-py3-none-any.whl",
  "./wheels/gltflib-1.0.13-py3-none-any.whl",
  "./wheels/google-3.0.0-py2.py3-none-any.whl",
  "./wheels/google_api_core-2.30.0-py3-none-any.whl",
  "./wheels/google_api_python_client-2.193.0-py3-none-any.whl",
  "./wheels/google_auth-2.47.0-py3-none-any.whl",
  "./wheels/google_auth-2.49.1-py3-none-any.whl",
  "./wheels/google_auth_httplib2-0.3.0-py3-none-any.whl",
  "./wheels/google_genai-1.68.0-py3-none-any.whl",
  "./wheels/googleapis_common_protos-1.73.0-py3-none-any.whl",
  "./wheels/gradio-6.10.0-py3-none-any.whl",
  "./wheels/gradio_client-2.4.0-py3-none-any.whl",
  "./wheels/groovy-0.1.2-py3-none-any.whl",
  "./wheels/grpcio-1.78.0-cp311-cp311-macosx_11_0_universal2.whl",
  "./wheels/grpcio-1.78.0-cp311-cp311-win_amd64.whl",
  "./wheels/h11-0.16.0-py3-none-any.whl",
  "./wheels/hf_gradio-0.3.0-py3-none-any.whl",
  "./wheels/hf_xet-1.4.2-cp37-abi3-macosx_11_0_arm64.whl",
  "./wheels/hf_xet-1.4.2-cp37-abi3-win_amd64.whl",
  "./wheels/httpcore-1.0.9-py3-none-any.whl",
  "./wheels/httplib2-0.31.2-py3-none-any.whl",
  "./wheels/httpx-0.28.1-py3-none-any.whl",
  "./wheels/httpx_sse-0.4.3-py3-none-any.whl",
  "./wheels/huggingface_hub-1.8.0-py3-none-any.whl",
  "./wheels/humanfriendly-10.0-py2.py3-none-any.whl",
  "./wheels/idna-3.11-py3-none-any.whl",
  "./wheels/imageio-2.37.3-py3-none-any.whl",
  "./wheels/imageio_ffmpeg-0.6.0-py3-none-macosx_11_0_arm64.whl",
  "./wheels/imageio_ffmpeg-0.6.0-py3-none-win_amd64.whl",
  "./wheels/importlib_metadata-9.0.0-py3-none-any.whl",
  "./wheels/ipython-8.38.0-py3-none-any.whl",
  "./wheels/ipython_pygments_lexers-1.1.1-py3-none-any.whl",
  "./wheels/jedi-0.19.2-py2.py3-none-any.whl",
  "./wheels/jinja2-3.1.6-py3-none-any.whl",
  "./wheels/jiter-0.13.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/jiter-0.13.0-cp311-cp311-win_amd64.whl",
  "./wheels/jsonschema-4.17.3-py3-none-any.whl",
  "./wheels/jsonschema-4.26.0-py3-none-any.whl",
  "./wheels/jsonschema_specifications-2023.3.3-py3-none-any.whl",
  "./wheels/jsonschema_specifications-2025.9.1-py3-none-any.whl",
  "./wheels/kiwisolver-1.5.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/kiwisolver-1.5.0-cp311-cp311-win_amd64.whl",
  "./wheels/loguru-0.7.3-py3-none-any.whl",
  "./wheels/markdown_it_py-4.0.0-py3-none-any.whl",
  "./wheels/markupsafe-3.0.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/markupsafe-3.0.3-cp311-cp311-win_amd64.whl",
  "./wheels/marshmallow-3.26.2-py3-none-any.whl",
  "./wheels/matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/matplotlib-3.10.8-cp311-cp311-win_amd64.whl",
  "./wheels/matplotlib_inline-0.2.1-py3-none-any.whl",
  "./wheels/mcp-1.26.0-py3-none-any.whl",
  "./wheels/mdurl-0.1.2-py3-none-any.whl",
  "./wheels/mmh3-5.2.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/mmh3-5.2.1-cp311-cp311-win_amd64.whl",
  "./wheels/moviepy-0.2.3.1-py2.py3-none-any.whl",
  "./wheels/moviepy-2.2.1-py3-none-any.whl",
  "./wheels/mpmath-1.3.0-py3-none-any.whl",
  "./wheels/multidict-6.7.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/multidict-6.7.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/multidict-6.7.1-cp311-cp311-win_amd64.whl",
  "./wheels/mypy_extensions-1.1.0-py3-none-any.whl",
  "./wheels/nest_asyncio-1.6.0-py3-none-any.whl",
  "./wheels/numpy-2.4.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/numpy-2.4.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/numpy-2.4.3-cp311-cp311-win_amd64.whl",
  "./wheels/onnxruntime-1.19.2-cp311-cp311-macosx_11_0_universal2.whl",
  "./wheels/onnxruntime-1.19.2-cp311-cp311-win_amd64.whl",
  "./wheels/openai-0.27.10-py3-none-any.whl",
  "./wheels/openai-1.39.0-py3-none-any.whl",
  "./wheels/openai-2.30.0-py3-none-any.whl",
  "./wheels/openresponses_types-2.3.0.post1-py3-none-any.whl",
  "./wheels/orjson-3.11.7-cp311-cp311-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl",
  "./wheels/orjson-3.11.7-cp311-cp311-win_amd64.whl",
  "./wheels/packaging-26.0-py3-none-any.whl",
  "./wheels/pandas-3.0.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pandas-3.0.1-cp311-cp311-win_amd64.whl",
  "./wheels/parso-0.8.6-py2.py3-none-any.whl",
  "./wheels/pexpect-4.9.0-py2.py3-none-any.whl",
  "./wheels/pillow-11.3.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pillow-11.3.0-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-12.1.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pillow-12.1.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/pillow-12.1.1-cp311-cp311-win_amd64.whl",
  "./wheels/proglog-0.1.12-py3-none-any.whl",
  "./wheels/prompt_toolkit-3.0.52-py3-none-any.whl",
  "./wheels/propcache-0.4.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/propcache-0.4.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/propcache-0.4.1-cp311-cp311-win_amd64.whl",
  "./wheels/proto_plus-1.27.1-py3-none-any.whl",
  "./wheels/protobuf-6.33.6-cp310-abi3-win_amd64.whl",
  "./wheels/protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl",
  "./wheels/protobuf-6.33.6-py3-none-any.whl",
  "./wheels/protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl",
  "./wheels/protobuf-7.34.1-cp310-abi3-win_amd64.whl",
  "./wheels/ptyprocess-0.7.0-py2.py3-none-any.whl",
  "./wheels/pure_eval-0.2.3-py3-none-any.whl",
  "./wheels/py_rust_stemmers-0.1.5-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/py_rust_stemmers-0.1.5-cp311-none-win_amd64.whl",
  "./wheels/pyasn1-0.6.3-py3-none-any.whl",
  "./wheels/pyasn1_modules-0.4.2-py3-none-any.whl",
  "./wheels/pycparser-3.0-py3-none-any.whl",
  "./wheels/pydantic-1.10.26-py3-none-any.whl",
  "./wheels/pydantic-2.12.5-py3-none-any.whl",
  "./wheels/pydantic_core-2.41.5-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pydantic_core-2.41.5-cp311-cp311-win_amd64.whl",
  "./wheels/pydantic_settings-2.13.1-py3-none-any.whl",
  "./wheels/pydub-0.25.1-py2.py3-none-any.whl",
  "./wheels/pygltflib-1.16.5-py3-none-any.whl",
  "./wheels/pygments-2.19.2-py3-none-any.whl",
  "./wheels/pyjwt-2.12.1-py3-none-any.whl",
  "./wheels/pyparsing-3.3.2-py3-none-any.whl",
  "./wheels/pyrsistent-0.20.0-py3-none-any.whl",
  "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/python_dotenv-1.2.2-py3-none-any.whl",
  "./wheels/python_fcl-0.7.0.10-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/python_fcl-0.7.0.10-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/python_fcl-0.7.0.10-cp311-cp311-win_amd64.whl",
  "./wheels/python_multipart-0.0.22-py3-none-any.whl",
  "./wheels/pytz-2026.1.post1-py2.py3-none-any.whl",
  "./wheels/pyyaml-6.0.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/pyyaml-6.0.3-cp311-cp311-win_amd64.whl",
  "./wheels/referencing-0.23.0-py3-none-any.whl",
  "./wheels/referencing-0.37.0-py3-none-any.whl",
  "./wheels/regex-2026.2.28-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/regex-2026.2.28-cp311-cp311-win_amd64.whl",
  "./wheels/requests-2.33.0-py3-none-any.whl",
  "./wheels/rich-14.3.3-py3-none-any.whl",
  "./wheels/rpds_py-0.30.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/rpds_py-0.30.0-cp311-cp311-win_amd64.whl",
  "./wheels/rsa-4.9.1-py3-none-any.whl",
  "./wheels/ruff-0.15.8-py3-none-macosx_11_0_arm64.whl",
  "./wheels/ruff-0.15.8-py3-none-win_amd64.whl",
  "./wheels/safehttpx-0.1.7-py3-none-any.whl",
  "./wheels/scipy-1.17.1-cp311-cp311-macosx_14_0_arm64.whl",
  "./wheels/scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/scipy-1.17.1-cp311-cp311-win_amd64.whl",
  "./wheels/semantic_version-2.10.0-py2.py3-none-any.whl",
  "./wheels/shellingham-1.5.4-py2.py3-none-any.whl",
  "./wheels/six-1.17.0-py2.py3-none-any.whl",
  "./wheels/sniffio-1.3.1-py3-none-any.whl",
  "./wheels/soupsieve-2.8.3-py3-none-any.whl",
  "./wheels/sse_starlette-3.3.3-py3-none-any.whl",
  "./wheels/stack_data-0.6.3-py3-none-any.whl",
  "./wheels/starlette-0.50.0-py3-none-any.whl",
  "./wheels/starlette-0.52.1-py3-none-any.whl",
  "./wheels/starlette-1.0.0-py3-none-any.whl",
  "./wheels/sympy-1.14.0-py3-none-any.whl",
  "./wheels/tabulate-0.9.0-py3-none-any.whl",
  "./wheels/tenacity-9.1.4-py3-none-any.whl",
  "./wheels/tencentcloud_sdk_python_ai3d-3.1.57-py2.py3-none-any.whl",
  "./wheels/tencentcloud_sdk_python_common-3.1.63-py2.py3-none-any.whl",
  "./wheels/tiktoken-0.3.3-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/tiktoken-0.3.3-cp311-cp311-win_amd64.whl",
  "./wheels/tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl",
  "./wheels/tokenizers-0.22.2-cp39-abi3-win_amd64.whl",
  "./wheels/tomlkit-0.13.3-py3-none-any.whl",
  "./wheels/tqdm-4.67.3-py3-none-any.whl",
  "./wheels/traitlets-5.14.3-py3-none-any.whl",
  "./wheels/trimesh-4.11.5-py3-none-any.whl",
  "./wheels/tripo3d-0.3.12-py3-none-any.whl",
  "./wheels/typer-0.24.1-py3-none-any.whl",
  "./wheels/typing_extensions-4.15.0-py3-none-any.whl",
  "./wheels/typing_inspect-0.9.0-py3-none-any.whl",
  "./wheels/typing_inspection-0.4.2-py3-none-any.whl",
  "./wheels/tzdata-2025.3-py2.py3-none-any.whl",
  "./wheels/uritemplate-4.2.0-py3-none-any.whl",
  "./wheels/urllib3-2.6.3-py3-none-any.whl",
  "./wheels/uvicorn-0.42.0-py3-none-any.whl",
  "./wheels/vdom-0.6-py3-none-any.whl",
  "./wheels/wcwidth-0.6.0-py3-none-any.whl",
  "./wheels/websockets-16.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/websockets-16.0-cp311-cp311-win_amd64.whl",
  "./wheels/win32_setctime-1.2.0-py3-none-any.whl",
  "./wheels/wrapt-2.1.2-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/wrapt-2.1.2-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl",
  "./wheels/wrapt-2.1.2-cp311-cp311-win_amd64.whl",
  "./wheels/yarl-1.23.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/yarl-1.23.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
  "./wheels/yarl-1.23.0-cp311-cp311-win_amd64.whl",
  "./wheels/zipp-3.23.0-py3-none-any.whl",
  "./wheels/zstandard-0.25.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/zstandard-0.25.0-cp311-cp311-win_amd64.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"

# Optional: advanced build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
]